### ISSUE TITLE
AttributeError: 'Scene' object has no attribute 'update'

### ISSUE THREAD

**Issue by delepoulle** [stig-atle/io_scene_pbrt#17]
When I try to export, I have this messsage with the new version.

Traceback (most recent call last):
  File "/home/samuel/.config/blender/2.80/scripts/addons/io_scene_pbrt-master/render_panel.py", line 16, in execute
    render_exporter.export_pbrt(bpy.data.scenes['Scene'].exportpath, bpy.data.scenes['Scene'], '{0:05d}'.format(frameNumber))
  File "/home/samuel/.config/blender/2.80/scripts/addons/io_scene_pbrt-master/render_exporter.py", line 974, in export_pbrt
    export_geometry(pbrt_file,scene)
  File "/home/samuel/.config/blender/2.80/scripts/addons/io_scene_pbrt-master/render_exporter.py", line 889, in export_geometry
    bpy.context.scene.update()
AttributeError: 'Scene' object has no attribute 'update'

location: <unknown location>:-1

**Comment by stig-atle** [comment]
Hi, I have pushed a small fix for this now.
Get the latest, see if it helps on your issue.
Sorry for pushing the fix 4 hours later, if I got the email on my phone earlier - then I would have fixed it faster.

Thank you for letting me know and taking the time to file the bug.

**Comment by delepoulle** [comment]
Yes, now the export works correctly. 

Thank you for your quick and efficient fix.

**Comment by stig-atle** [comment]
Thanks for the feedback. Closing the bug now since it's been fixed.
